name: Automated trader

on:
  schedule:
#    - cron: "0 0 * * *"   # ogni giorno alle 00:00 UTC
    # - cron: "0 8 * * *"   # ogni giorno alle 08:00 UTC
     - cron: "0 12 * * *"  # ogni giorno alle 12:00 UTC
    # - cron: "0 16 * * *"  # ogni giorno alle 16:00 UTC
  workflow_dispatch:
    inputs:
      reset:
        description: 'Set it to TRUE if you want to reinitialize the app data'
        required: true
        default: 'FALSE'

permissions:
  contents: write  # necessario per push

jobs:
  update:
    runs-on: ubuntu-latest

    # VARIABILI GLOBALI DEL JOB
    env:
      DB_DIR: data/db
      DB_NAME: italian_stocks.db

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- RICOSTRUZIONE DB PRIMA DEL RUN ---
      - name: Ricostruisci DB se frammentato
        run: |
          if ls "$DB_DIR/$DB_NAME".part* 1> /dev/null 2>&1; then
            echo "Ricostruzione del database da parti..."
            cat "$DB_DIR/$DB_NAME".part* > "$DB_DIR/$DB_NAME"
          else
            echo "Nessun frammento trovato, uso DB esistente se presente."
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies for Playwright
        run: sudo npx playwright install-deps

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Installa Playwright browsers
        run: playwright install

      - name: Run script
        run: python src/main.py
        env:
          RESET: ${{ github.event.inputs.reset }}
          PYTHONPATH: ${{ github.workspace }}

      # --- SPLIT DOPO IL RUN ---
      - name: Split DB in parti da 99 MB
        run: |
          DB_PATH="$DB_DIR/$DB_NAME"

          if [ -f "$DB_PATH" ]; then
            echo "Splitting database..."
            split -b 99m "$DB_PATH" "${DB_PATH}.part"
            rm "$DB_PATH"
          else
            echo "Database non trovato, nessuno split."
          fi

      # --- COMMIT DEI FRAMMENTI ---
      - name: Commit updated database
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Aggiornamento dati azioni italiane" || echo "Nessun cambiamento"
          git push
